#!/bin/bash

# Set file permissions for OCI CLI config
find config/.oci -type f -exec chmod 600 {} \;

# Set file permissions for GPG keys
find config/.gnupg -type d -exec chmod 700 {} \;
find config/.gnupg -type f -exec chmod 600 {} \;

# htop changes its configuration file with view changes, so ignore
git update-index --assume-unchanged config/.config/htop/htoprc
