#!/bin/bash

# Ignore additional GnuPG public keyrings
git update-index --assume-unchanged config/.gnupg/pubring.kbx

# htop changes its configuration file with view changes, so ignore
git update-index --assume-unchanged config/.config/htop/htoprc

# copyq changes its configuration file when makng new tabs, so ignore
git update-index --assume-unchanged config/.config/copyq/copyq.ini

# XnView changes its configuration file in use, so ignore
git update-index --assume-unchanged config/.config/xnviewmp/xnview.ini
git update-index --assume-unchanged config/.config/xnviewmp/default.bar
git update-index --assume-unchanged config/.config/xnviewmp/default.keys

# Set file permissions for OCI CLI config
find config/.oci -type f -exec chmod 600 {} \;

# Set file permissions for GPG keys
find config/.gnupg -type d -exec chmod 700 {} \;
find config/.gnupg -type f -exec chmod 600 {} \;
