#!/bin/bash

# htop changes its configuration file with view changes, so ignore
git update-index --assume-unchanged config/.config/htop/htoprc

# copyq changes its configuration file when makng new tabs, so ignore
git update-index --assume-unchanged config/.config/copyq/copyq.ini

# XnView changes its configuration file in use, so ignore
git update-index --assume-unchanged config/.config/xnviewmp/xnview.ini
git update-index --assume-unchanged config/.config/xnviewmp/default.bar
git update-index --assume-unchanged config/.config/xnviewmp/default.keys
