#!/bin/bash

# Unstash pre-rebase stash
stash_message="Pre-rebase stash"
stash_id=$(git stash list | grep "$stash_message" | cut -d: -f1)
if [[ -n $stash_id ]]; then
  git stash pop "$stash_id"
fi

# htop changes its configuration file with view changes, so ignore
git update-index --assume-unchanged config/.config/htop/htoprc

# copyq changes its configuration file when makng new tabs, so ignore
git update-index --assume-unchanged config/.config/copyq/copyq.ini

# XnView changes its configuration file in use, so ignore
git update-index --assume-unchanged config/.config/xnviewmp/xnview.ini
git update-index --assume-unchanged config/.config/xnviewmp/default.bar
git update-index --assume-unchanged config/.config/xnviewmp/default.keys
