#!/bin/bash

# Make sure we are not in the active .dotfiles directory
last_arg=$(echo "$*" | awk '{print $NF}')
if [[ $(pwd) =~ ^$HOME/.dotfiles/* && "$last_arg" != "HEAD~"* && $MSYSTEM != MINGW64 ]]; then
  echo "You are in the active .dotfiles directory. Cancelling rebase."
  exit 1
fi

# Skip hook if the action is a merge
if [ "$GIT_REFLOG_ACTION" == "pull --no-ff" ]; then
  exit 0
fi

# Stop ignoring htop config for rebasing
git update-index --no-assume-unchanged config/.config/htop/htoprc

# Stop ignoring copyq config file for rebasing
git update-index --no-assume-unchanged config/.config/copyq/copyq.ini

# Stop ignoring xnview config for rebasing
git update-index --no-assume-unchanged config/.config/xnviewmp/xnview.ini
git update-index --no-assume-unchanged config/.config/xnviewmp/default.bar
git update-index --no-assume-unchanged config/.config/xnviewmp/default.keys

# Stash any changes
git stash -m "Pre-rebase stash"
