# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Import additional configuration files
import:
  - ~/.dotfiles/config/.config/alacritty/alacritty.main.yml

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: "Iosevka Term"
    style: Regular

  # Bold font face
  bold:
    style: Bold

  # Italic font face
  italic:
    style: Italic

  # Bold italic font face
  bold_italic:
    style: Bold Italic

  # Point size
  size: 12.0
