# Configuration for Alacritty, the GPU enhanced terminal emulator.

window:
  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

# Key bindings
key_bindings:
  - { key: Paste,                                action: Paste          }
  - { key: Copy,                                 action: Copy           }
  - { key: L,         mods: Control,             action: ClearLogNotice }
  - { key: PageUp,    mods: Shift,   mode: ~Alt, action: ScrollPageUp,  }
  - { key: PageDown,  mods: Shift,   mode: ~Alt, action: ScrollPageDown }
  - { key: Home,      mods: Shift,   mode: ~Alt, action: ScrollToTop,   }
  - { key: End,       mods: Shift,   mode: ~Alt, action: ScrollToBottom }

  # (Windows, Linux, and BSD only)
  - { key: V,              mods: Control|Shift,           action: Paste            }
  - { key: C,              mods: Control|Shift,           action: Copy             }
  - { key: F,              mods: Control|Shift,           action: SearchForward    }
  - { key: B,              mods: Control|Shift,           action: SearchBackward   }
  - { key: Insert,         mods: Shift,                   action: PasteSelection   }
  - { key: Key0,           mods: Control,                 action: ResetFontSize    }
  - { key: Equals,         mods: Control,                 action: IncreaseFontSize }
  - { key: Plus,           mods: Control,                 action: IncreaseFontSize }
  - { key: NumpadAdd,      mods: Control,                 action: IncreaseFontSize }
  - { key: Minus,          mods: Control,                 action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Control,                 action: DecreaseFontSize }

  # (Windows only)
  - { key: Return,   mods: Alt,           action: ToggleFullscreen }

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: Hack
    style: Regular

  # Bold font face
  bold:
    style: Bold

  # Italic font face
  italic:
    style: Italic

  # Bold italic font face
  bold_italic:
    style: Bold Italic

  # Point size
  size: 13.0

draw_bold_text_with_bright_colors: true

# Mouse selection
selection:
  save_to_clipboard: true

# Theme
colors:
  name: Monokai (dark)
  author: Chris Kempson
  primary:
    background: "#272822"
    foreground: "#f8f8f2"
  cursor:
    text: "#272822"
    cursor: "#f8f8f2"
  normal:
    black: "#272822"
    red: "#f92672"
    green: "#a6e22e"
    yellow: "#f4bf75"
    blue: "#66d9ef"
    magenta: "#ae81ff"
    cyan: "#a1efe4"
    white: "#f8f8f2"
  bright:
    black: "#75715e"
    red: "#f92672"
    green: "#a6e22e"
    yellow: "#f4bf75"
    blue: "#66d9ef"
    magenta: "#ae81ff"
    cyan: "#a1efe4"
    white: "#f9f8f5"
