# Configuration for Alacritty, the GPU enhanced terminal emulator.

window:
  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

# Key bindings
key_bindings:
  - { key: Return, mods: Alt, action: ToggleFullscreen }

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: Hack
    style: Regular

  # Bold font face
  bold:
    style: Bold

  # Italic font face
  italic:
    style: Italic

  # Bold italic font face
  bold_italic:
    style: Bold Italic

  # Point size
  size: 13.0

draw_bold_text_with_bright_colors: true

# Mouse selection
selection:
  save_to_clipboard: true

# Theme
colors:
  name: Monokai (dark)
  author: Chris Kempson
  primary:
    background: "#272822"
    foreground: "#f8f8f2"
  cursor:
    text: "#272822"
    cursor: "#f8f8f2"
  normal:
    black: "#272822"
    red: "#f92672"
    green: "#a6e22e"
    yellow: "#f4bf75"
    blue: "#66d9ef"
    magenta: "#ae81ff"
    cyan: "#a1efe4"
    white: "#f8f8f2"
  bright:
    black: "#75715e"
    red: "#f92672"
    green: "#a6e22e"
    yellow: "#f4bf75"
    blue: "#66d9ef"
    magenta: "#ae81ff"
    cyan: "#a1efe4"
    white: "#f9f8f5"
