# Configuration for Alacritty, the GPU enhanced terminal emulator.

window:
  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 5
    y: 0

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

  # Window title
  title: Terminal

# Key bindings
key_bindings:
  - { key: Paste,                                action: Paste          }
  - { key: Copy,                                 action: Copy           }
  - { key: PageUp,    mods: Shift,   mode: ~Alt, action: ScrollPageUp,  }
  - { key: PageDown,  mods: Shift,   mode: ~Alt, action: ScrollPageDown }
  - { key: Home,      mods: Shift,   mode: ~Alt, action: ScrollToTop,   }
  - { key: End,       mods: Shift,   mode: ~Alt, action: ScrollToBottom }

  # (Windows, Linux, and BSD only)
  - { key: V,              mods: Control|Shift,           action: Paste            }
  - { key: C,              mods: Control|Shift,           action: Copy             }
  - { key: F,              mods: Control|Shift,           action: SearchForward    }
  - { key: B,              mods: Control|Shift,           action: SearchBackward   }
  - { key: Insert,         mods: Shift,                   action: PasteSelection   }
  - { key: Key0,           mods: Control,                 action: ResetFontSize    }
  - { key: Equals,         mods: Control,                 action: IncreaseFontSize }
  - { key: Plus,           mods: Control,                 action: IncreaseFontSize }
  - { key: NumpadAdd,      mods: Control,                 action: IncreaseFontSize }
  - { key: Minus,          mods: Control,                 action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Control,                 action: DecreaseFontSize }

  # (Windows only)
  - { key: Return,         mods: Alt,                     action: ToggleFullscreen }

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: "Hack Nerd Font"
    style: Regular

  # Bold font face
  bold:
    style: Bold

  # Italic font face
  italic:
    style: Italic

  # Bold italic font face
  bold_italic:
    style: Bold Italic

  # Point size
  size: 13.0

draw_bold_text_with_bright_colors: true

# Mouse selection
selection:
  save_to_clipboard: true

# Theme
colors:
  # Default colors
  primary:
    background: '#292C3E'
    foreground: '#EBEBEB'

  # Cursor colors
  cursor:
    text: '#0d0d0d'
    cursor: '#FF261E'

  # Normal colors
  normal:
    black: '#0d0d0d'
    red: '#FF301B'
    green: '#A0E521'
    yellow: '#FFC620'
    blue: '#1BA6FA'
    magenta: '#8763B8'
    cyan: '#21DEEF'
    white: '#EBEBEB'

  # Bright colors
  bright:
    black: '#6D7070'
    red: '#FF4352'
    green: '#B8E466'
    yellow: '#FFD750'
    blue: '#1BA6FA'
    magenta: '#A578EA'
    cyan: '#73FBF1'
    white: '#FEFEF8'

# Bell
bell:
  animation: EaseOutExpo
  duration: 10
  color: '#ffffff'
