" VIM CONFIGURATION

if has('unix')
  source ~/.dotfiles/config/.config/vim/vimrc.d/xdg.vim
endif
if !has("gui_running")
  syntax on
  colorscheme gruvbox8_soft
  set background=dark
  if has('unix')
    source ~/.dotfiles/config/.config/vim/vimrc.d/plugins.vim
  elseif has('win32')
    source ~/vimfiles/vimrc.d/plugins.vim
  endif
endif
if has('unix')
  source ~/.dotfiles/config/.config/vim/vimrc.d/common.vim
  source ~/.dotfiles/config/.config/vim/vimrc.d/autocmds.vim
  source ~/.dotfiles/config/.config/vim/vimrc.d/pluginconfig.vim
elseif has('win32')
  source ~/vimfiles/vimrc.d/common.vim
  source ~/vimfiles/vimrc.d/autocmds.vim
  source ~/vimfiles/vimrc.d/pluginconfig.vim
endif

if has('unix') | set noundofile | elseif has('win32') | set undofile | endif
