" VIM CONFIGURATION

if has('unix')
  source ~/.config/vim/vimrc.d/xdg.vim
elseif has('win32')
  source ~/vimfiles/vimrc.d/xdg.vim
endif
if !has('gui_running')
  syntax on
  colorscheme gruvbox8_soft
  set background=dark
  " Change cursor depending on mode, like in nvim
  let &t_SI = "\<Esc>[6 q"
  let &t_SR = "\<Esc>[4 q"
  let &t_EI = "\<Esc>[2 q"
  if has('unix')
    source ~/.config/vim/vimrc.d/plugins.vim
  elseif has('win32')
    source ~/vimfiles/vimrc.d/plugins.vim
  endif
endif
if has('unix')
  source ~/.config/vim/vimrc.d/common.vim
  source ~/.config/vim/vimrc.d/autocmds.vim
  source ~/.config/vim/vimrc.d/pluginconfig.vim
elseif has('win32')
  source ~/vimfiles/vimrc.d/common.vim
  source ~/vimfiles/vimrc.d/autocmds.vim
  source ~/vimfiles/vimrc.d/pluginconfig.vim
endif
