name: Build and upgrade git-crypt
on:
  [workflow_dispatch]

jobs:
  build_on_ARM:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [armv7l, aarch64]
        include:
          - arch: armv7l
            cpu: cortex-a7
            base_image: raspios_lite:latest
          - arch: aarch64
            cpu: cortex-a53
            base_image: raspios_lite_arm64:latest

    steps:
      - name: Get release version
        run: |
          export tag="$(curl -s https://api.github.com/repos/AGWA/git-crypt/releases/latest | jq -r '.tag_name')"
          echo "version=${tag}" >> $GITHUB_ENV

      - name: Download and extract git-crypt source code
        run: |
          name="${{ env.version }}.tar.gz"
          wget -q "$(curl -s https://api.github.com/repos/AGWA/git-crypt/releases/latest | jq -r '.tarball_url')" -O ${{ env.version }}.tar.gz
          tar -xvf ${{ env.version }}.tar.gz

      - name: Build for ${{ matrix.arch }}
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          copy_artifact_path: ../usr/local/bin/git-crypt
          copy_artifact_dest: .
          image_additional_mb: 2048
          commands: |
            apt-get install -y make g++ libssl-dev
            cd AGWA-git-crypt-*
            LDFLAGS='-static -lcrypto -ldl -Wl,--whole-archive -lpthread -Wl,--no-whole-archive' make
            make install

      - name: Upload artefacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch }}-binary
          path: |
            git-crypt

  build_on_x86_64_and_commit:
    needs: [build_on_ARM]
    runs-on: ubuntu-20.04

    steps:
      - name: Get release version
        run: |
          export tag="$(curl -s https://api.github.com/repos/AGWA/git-crypt/releases/latest | jq -r '.tag_name')"
          echo "version=${tag}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.github_token }}

      - name: Download and extract git-crypt source code
        run: |
          name="${{ env.version }}.tar.gz"
          wget -q "$(curl -s https://api.github.com/repos/AGWA/git-crypt/releases/latest | jq -r '.tarball_url')" -O ${{ env.version }}.tar.gz
          tar -xvf ${{ env.version }}.tar.gz

      - name: Build for x86_84
        run: |
          sudo apt-get install -y make g++ libssl-dev xsltproc docbook-xsl
          cd AGWA-git-crypt-*
          LDFLAGS='-static -lcrypto -ldl -Wl,--whole-archive -lpthread -Wl,--no-whole-archive' make ENABLE_MAN=yes

      - name: Move files
        run: |
          mv AGWA-git-crypt-*/git-crypt bin/x86_64
          gzip AGWA-git-crypt-*/man/man1/git-crypt.1
          mv AGWA-git-crypt-*/man/man1/git-crypt.1.gz bin/man/man1
          rm -rf ${{ env.version }}* AGWA-git-crypt-*

      - name: Download armv7l artefacts
        uses: actions/download-artifact@v3
        with:
          name: armv7l-binary
          path: bin/armv7l

      - name: Download aarch64 artefacts
        uses: actions/download-artifact@v3
        with:
          name: aarch64-binary
          path: bin/aarch64

      - name: Commit and push to repository
        run: |
          git config --global user.name "eggbean"
          git config --global user.email 815311+eggbean@users.noreply.github.com
          git add --all
          git status
          tag="$(curl -s https://api.github.com/repos/AGWA/git-crypt/releases/latest | jq -r '.tag_name')"
          git commit -m "Upgrade git-crypt to ${tag#*-}"
          git push
