name: Build static tmux
on:
  [workflow_dispatch]

jobs:
  build_on_ARM:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7l, aarch64]
        include:
          - arch: armv7l
            cpu: cortex-a7
            base_image: raspios_lite:latest
          - arch: aarch64
            cpu: cortex-a53
            base_image: raspios_lite_arm64:latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.github_token }}

      - name: Upgrade buildscript
        run: wget https://github.com/mjakob-gh/build-static-tmux/raw/master/build-static-tmux.sh -O bin/scripts/build-static-tmux.sh

      - name: Build for ${{ matrix.arch }}
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          copy_artifact_path: ../tmp/tmux-static/bin/tmux
          copy_artifact_dest: .
          image_additional_mb: 1024
          commands: |
              test $(uname -m) = ${{ matrix.arch }}
              /bin/sh bin/scripts/build-static-tmux.sh
              cp ../tmp/tmux-static/bin/tmux .

      - name: Upload artefact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch }}-binary
          path: tmux

  build_on_x86_64_and_commit:
    needs: [build_on_ARM]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.github_token }}

      - name: Upgrade buildscript
        run: wget https://github.com/mjakob-gh/build-static-tmux/raw/master/build-static-tmux.sh -O bin/scripts/build-static-tmux.sh

      - name: Build for x86_84
        run: |
          /bin/sh bin/scripts/build-static-tmux.sh
          mv /tmp/tmux-static/bin/tmux bin/x86_64
          mv /tmp/tmux-static/share/man/man1/tmux.1 bin/man/man1
          gzip -f bin/man/man1/tmux.1

      - name: Download armv7l artefact
        uses: actions/download-artifact@v3
        with:
          name: armv7l-binary
          path: bin/armv7l

      - name: Download aarch64 artefact
        uses: actions/download-artifact@v3
        with:
          name: aarch64-binary
          path: bin/aarch64

      - name: Get bash completion file
        run: wget https://github.com/Bash-it/bash-it/raw/master/completion/available/tmux.completion.bash -O bin/completions/tmux.completion.bash

      - name: Commit and push to repository
        run: |
          git config --global user.name "eggbean"
          git config --global user.email 815311+eggbean@users.noreply.github.com
          git add --all
          git status
          tag="$(curl -s https://api.github.com/repos/tmux/tmux/releases/latest | jq -r '.tag_name')"
          git commit -m "Upgrade tmux to ${tag}"
          git push
