name: Upgrade yq
on:
  [workflow_dispatch]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release version
        run: |
          export tag="$(curl -s https://api.github.com/repos/mikefarah/yq/releases/latest | jq -r '.tag_name')"
          echo "version=${tag}" >> $GITHUB_ENV

      - name: Download binaries and man file
        run: |
          wget -q https://github.com/mikefarah/yq/releases/download/${{ env.version }}/yq_linux_amd64 -O bin/x86_64/yq
          chmod +x bin/x86_64/yq

          wget -q https://github.com/mikefarah/yq/releases/download/${{ env.version }}/yq_linux_arm -O bin/armv7l/yq
          chmod +x bin/armv7l/yq

          wget -q https://github.com/mikefarah/yq/releases/download/${{ env.version }}/yq_linux_arm64 -O bin/aarch64/yq
          chmod +x bin/aarch64/yq

          wget -q https://github.com/mikefarah/yq/releases/download/${{ env.version }}/yq_man_page_only.tar.gz
          tar -C bin/man/man1 -xf yq_man_page_only.tar.gz yq.1
          rm yq_man_page_only.tar.gz
          gzip -f bin/man/man1/yq.1

          bin/x86_64/yq shell-completion bash > bin/bash-completions/yq.bash
          bin/x86_64/yq shell-completion zsh > bin/zsh-completions/_yq

      - name: Commit and push to repository
        run: |
          git config --global user.name "eggbean"
          git config --global user.email 815311+eggbean@users.noreply.github.com
          git add --all
          git status
          git commit -m "[Action] Upgrade yq to ${{ env.version }}"
          git push
