name: Upgrade git-lfs
on:
  [workflow_dispatch]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release version
        run: |
          export tag="$(curl -s https://api.github.com/repos/git-lfs/git-lfs/releases/latest | jq -r '.tag_name')"
          echo "version=${tag}" >> $GITHUB_ENV

      - name: Download binaries and man file
        run: |
          version=${{ env.version }}
          numberonly="${version:1}"

          wget -q https://github.com/git-lfs/git-lfs/releases/download/"$version"/git-lfs-linux-amd64-"$version".tar.gz
          tar -xf git-lfs-linux-amd64-"$version".tar.gz
          mv git-lfs-"$numberonly"/git-lfs bin/x86_64
          gzip git-lfs-"$numberonly"/man/man{1,5}/*
          rm -rf bin/man/man{1,5}/git-lfs*
          mv git-lfs-"$numberonly"/man/man1/* bin/man/man1
          [ ! -d bin/man/man5 ] && mkdir bin/man/man5
          mv git-lfs-"$numberonly"/man/man5/* bin/man/man5
          rm -rf git-lfs-"$numberonly"/{CHANGELOG.md,install.sh,man/html,README.md} git-lfs-linux-amd64-"$version".tar.gz

          wget -q https://github.com/git-lfs/git-lfs/releases/download/"$version"/git-lfs-linux-arm-"$version".tar.gz
          tar -xf git-lfs-linux-arm-"$version".tar.gz
          mv git-lfs-"$numberonly"/git-lfs bin/armv7l
          rm -rf git-lfs-"$numberonly"/{CHANGELOG.md,install.sh,man,README.md} git-lfs-linux-arm-"$version".tar.gz

          wget -q https://github.com/git-lfs/git-lfs/releases/download/"$version"/git-lfs-linux-arm64-"$version".tar.gz
          tar -xf git-lfs-linux-arm64-"$version".tar.gz
          mv git-lfs-"$numberonly"/git-lfs bin/aarch64
          rm -rf git-lfs-"$numberonly"/{CHANGELOG.md,install.sh,man,README.md} git-lfs-linux-arm64-"$version".tar.gz

      - name: Commit and push to repository
        run: |
          git config --global user.name "eggbean"
          git config --global user.email 815311+eggbean@users.noreply.github.com
          git add --all
          git status
          git commit -m "Upgrade git-lfs to ${{ env.version }}"
          git push
