name: Upgrade mclient
on:
  [workflow_dispatch]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release version
        run: |
          export tag="$(curl -s https://api.github.com/repos/minio/mc/releases/latest | jq -r '.tag_name')"
          echo "version=${tag}" >> $GITHUB_ENV

      - name: Download binaries
        run: |
          wget -q https://dl.min.io/client/mc/release/linux-amd64/"mc.${{ env.version }}"
          sha256="$(curl -s https://dl.min.io/client/mc/release/linux-amd64/mc.${{ env.version }}.sha256sum)"
          [ "$( sha256sum "mc.${{ env.version }}" | awk '{ print $1 }' )" == "$( echo "${sha256}" | awk '{ print $1 }' )" ] || exit 1
          mv "mc.${{ env.version }}" bin/x86_64/mclient

          wget -q https://dl.min.io/client/mc/release/linux-arm/"mc.${{ env.version }}"
          sha256="$(curl -s https://dl.min.io/client/mc/release/linux-arm/mc.${{ env.version }}.sha256sum)"
          [ "$( sha256sum "mc.${{ env.version }}" | awk '{ print $1 }' )" == "$( echo "${sha256}" | awk '{ print $1 }' )" ] || exit 1
          mv "mc.${{ env.version }}" bin/armv7l/mclient

          wget -q https://dl.min.io/client/mc/release/linux-arm64/"mc.${{ env.version }}"
          sha256="$(curl -s https://dl.min.io/client/mc/release/linux-arm64/mc.${{ env.version }}.sha256sum)"
          [ "$( sha256sum "mc.${{ env.version }}" | awk '{ print $1 }' )" == "$( echo "${sha256}" | awk '{ print $1 }' )" ] || exit 1
          mv "mc.${{ env.version }}" bin/aarch64/mclient

          chmod +x bin/{x86_64,armv7l,aarch64}/mclient

      - name: Commit and push to repository
        run: |
          git config --global user.name "eggbean"
          git config --global user.email 815311+eggbean@users.noreply.github.com
          git add --all
          git status
          git commit -m "Upgrade MinIO Client to ${{ env.version }}"
          git push
