name: Upgrade tre
on:
  [workflow_dispatch]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and extract tarballs
        run: |
          nameregex='^tre-v\d[\d.]+?\d?-arm-unknown-linux-gnueabihf\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/dduan/tre/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar -xvf tre-v*-arm-unknown-linux-gnueabihf.tar.gz
          mv tre bin/armv7l
          mv tre.1 bin/man/man1
          gzip -f bin/man/man1/tre.1
          rm tre-v*-arm-unknown-linux-gnueabihf.tar.gz

          nameregex='^tre-v\d[\d.]+?\d?-x86_64-unknown-linux-musl\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/dduan/tre/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar -xvf tre-v*-x86_64-unknown-linux-musl.tar.gz
          mv tre bin/x86_64
          rm tre.1 tre-v*-x86_64-unknown-linux-musl.tar.gz

          wget -q https://raw.githubusercontent.com/dduan/tre/main/scripts/completion/tre.bash -O bin/bash-completions/tre.bash
          wget -q https://raw.githubusercontent.com/dduan/tre/main/scripts/completion/_tre -O bin/zsh-completions/_tre

      - name: Commit and push to repository
        run: |
          git config --global user.name "eggbean"
          git config --global user.email 815311+eggbean@users.noreply.github.com
          git add --all
          git status
          tag="$(curl -s https://api.github.com/repos/dduan/tre/releases/latest | jq -r '.tag_name')"
          git commit -m "[Action] Upgrade tre to ${tag}"
          git push
