name: Upgrade tidy-viewer
on:
  [workflow_dispatch]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release version
        run: |
          export tag="$(curl -s https://api.github.com/repos/alexhallam/tv/releases/latest | jq -r '.tag_name')"
          echo "version=${tag}" >> $GITHUB_ENV

      - name: Download and extract tarball
        run: |
          nameregex='^tidy-viewer-\d[\d.]+?\d?-x86_64-unknown-linux-musl.tar.gz$'
          url="$(curl -s https://api.github.com/repos/alexhallam/tv/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          file="${url##*/}"
          wget -q "${url}"
          tar xvf "${file}"
          rm -rf "${file}" tidy-viewer-${{ env.version }}-x86_64-unknown-linux-musl/{README.md,UNLICENSE}
          mv tidy-viewer-${{ env.version }}-x86_64-unknown-linux-musl/tidy-viewer bin/x86_64

      - name: Commit and push to repository
        run: |
          git config --global user.name "eggbean"
          git config --global user.email 815311+eggbean@users.noreply.github.com
          git add --all
          git status
          git commit -m "Upgrade tidy-viewer to ${{ env.version }} for x86_64"
          git push
