name: Upgrade GitHub CLI
on:
  [workflow_dispatch]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download and extract tarballs
      run: |
        nameregex='^gh_\d[\d.]+?\d?_linux_amd64\.tar\.gz$'
        wget -q "$(curl -s https://api.github.com/repos/cli/cli/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
        tar --wildcards --strip-components=2 -C bin/x86_64 -xvf gh_*.tar.gz gh_*/bin/gh
        rm bin/man/man1/gh*.gz
        tar --wildcards --overwrite --strip-components=4 -C bin/man/man1 -xvf gh_*.tar.gz gh_*/share/man/man1/*
        gzip -q bin/man/man1/gh*.1
        rm gh_*.tar.gz

        nameregex='^gh_\d[\d.]+?\d?_linux_arm64\.tar\.gz$'
        wget -q "$(curl -s https://api.github.com/repos/cli/cli/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
        tar --wildcards --strip-components=2 -C bin/aarch64 -xvf gh_*.tar.gz gh_*/bin/gh
        rm gh_*.tar.gz

        nameregex='^gh_\d[\d.]+?\d?_linux_armv6\.tar\.gz$'
        wget -q "$(curl -s https://api.github.com/repos/cli/cli/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
        tar --wildcards --strip-components=2 -C bin/armv7l -xvf gh_*.tar.gz gh_*/bin/gh
        rm gh_*.tar.gz

    - name: Commit and push to repository
      run: |
        git config --global user.name "eggbean"
        git config --global user.email 815311+eggbean@users.noreply.github.com
        git add --all
        git status
        tag="$(curl -s https://api.github.com/repos/cli/cli/releases/latest | jq -r '.tag_name')"
        git commit -m "Upgrade GitHub CLI to ${tag}"
        git push
