name: Upgrade dnslookup
on:
  [workflow_dispatch]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and extract tarballs
        run: |
          nameregex='^dnslookup-linux-amd64-v\d[\d.]+?\d?\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/ameshkov/dnslookup/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar --exclude='README.md' --exclude='LICENSE' -xvf dnslookup-linux-amd64-v*.tar.gz
          mv linux-amd64/dnslookup bin/x86_64 
          rm dnslookup-linux-amd64-v*.tar.gz

          nameregex='^dnslookup-linux-arm-v\d[\d.]+?\d?\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/ameshkov/dnslookup/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar --exclude='README.md' --exclude='LICENSE' -xvf dnslookup-linux-arm-v*.tar.gz
          mv linux-arm/dnslookup bin/armv7l
          rm dnslookup-linux-arm-v*.tar.gz

          nameregex='^dnslookup-linux-arm64-v\d[\d.]+?\d?\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/ameshkov/dnslookup/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar --exclude='README.md' --exclude='LICENSE' -xvf dnslookup-linux-arm64-v*.tar.gz
          mv linux-arm64/dnslookup bin/aarch64
          rm dnslookup-linux-arm64-v*.tar.gz

      - name: Commit and push to repository
        run: |
          git config --global user.name "eggbean"
          git config --global user.email 815311+eggbean@users.noreply.github.com
          git add --all
          git status
          tag="$(curl -s https://api.github.com/repos/ameshkov/dnslookup/releases/latest | jq -r '.tag_name')"
          git commit -m "Upgrade dnslookup to ${tag}"
          git push
