name: Upgrade terragrunt
on:
  [workflow_dispatch]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download
        run: |
          name='terragrunt_linux_amd64'
          wget -q "$(curl -s https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | jq -r '.assets[] | select(.name == $name).browser_download_url' --arg name "${name}")"
          chmod +x "${name}"
          mv "${name}" bin/x86_64/terragrunt

          name='terragrunt_linux_arm64'
          wget -q "$(curl -s https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | jq -r '.assets[] | select(.name == $name).browser_download_url' --arg name "${name}")"
          chmod +x "${name}"
          mv "${name}" bin/aarch64/terragrunt

      - name: Commit and push to repository
        run: |
          git config --global user.name "eggbean"
          git config --global user.email 815311+eggbean@users.noreply.github.com
          git add --all
          git status
          tag="$(curl -s https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | jq -r '.tag_name')"
          git commit -m "[Action] Upgrade terragrunt to ${tag}"
          git push
