name: Upgrade zoxide
on:
  [workflow_dispatch]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and extract tarballs
        run: |
          nameregex='^zoxide-\d[\d.]+?\d?-x86_64-unknown-linux-musl\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/ajeetdsouza/zoxide/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar --exclude='README.md' -xvf zoxide-*-x86_64-unknown-linux-musl.tar.gz
          mv zoxide bin/x86_64
          gzip -f man/man1/zoxide*.1
          mv man/man1/zoxide*.1.gz bin/man/man1
          mv completions/zoxide.bash bin/bash-completions
          mv completions/_zoxide bin/zsh-completions
          rm -rf CHANGELOG.md LICENSE completions/
          rm zoxide-*-x86_64-unknown-linux-musl.tar.gz

          nameregex='^zoxide-\d[\d.]+?\d?-aarch64-unknown-linux-musl\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/ajeetdsouza/zoxide/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar -C bin/aarch64 -xvf zoxide-*-aarch64-unknown-linux-musl.tar.gz zoxide
          rm zoxide-*-aarch64-unknown-linux-musl.tar.gz

          nameregex='^zoxide-\d[\d.]+?\d?-armv7-unknown-linux-musleabihf\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/ajeetdsouza/zoxide/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar -C bin/armv7l -xvf zoxide-*-armv7-unknown-linux-musleabihf.tar.gz zoxide
          rm zoxide-*-armv7-unknown-linux-musleabihf.tar.gz

      - name: Commit and push to repository
        run: |
          git config --global user.name "eggbean"
          git config --global user.email 815311+eggbean@users.noreply.github.com
          git add --all
          git status
          tag="$(curl -s https://api.github.com/repos/ajeetdsouza/zoxide/releases/latest | jq -r '.tag_name')"
          git commit --fixup=amend::/'\[Action\] Upgrade zoxide' -m "[Action] Upgrade zoxide to ${tag}"
          git push
