name: Upgrade bat
on:
  [workflow_dispatch]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and extract tarballs
        run: |
          nameregex='^bat-v\d[\d.]+?\d?-aarch64-unknown-linux-gnu\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/sharkdp/bat/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar --wildcards --strip-components=1 -C bin/aarch64 -xvf bat-v*-unknown-linux-gnu.tar.gz bat-v*-unknown-linux-gnu/bat
          tar --wildcards --strip-components=1 -C bin/man/man1 -xvf bat-v*-unknown-linux-gnu.tar.gz bat-v*-unknown-linux-gnu/bat.1
          gzip -f bin/man/man1/bat.1 2>/dev/null
          tar --wildcards --strip-components=2 -C bin/bash-completions -xvf bat-v*-unknown-linux-gnu.tar.gz bat-v*-unknown-linux-gnu/autocomplete/bat.bash
          tar --wildcards --strip-components=2 -C bin/zsh-completions -xvf bat-v*-unknown-linux-gnu.tar.gz bat-v*-unknown-linux-gnu/autocomplete/bat.zsh
          mv bin/zsh-completions/{bat.zsh,_bat}
          rm bat-v*-unknown-linux-gnu.tar.gz

          nameregex='^bat-v\d[\d.]+?\d?-arm-unknown-linux-gnueabihf\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/sharkdp/bat/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar --wildcards --strip-components=1 -C bin/armv7l -xvf bat-v*-unknown-linux-gnueabihf.tar.gz bat-v*-unknown-linux-gnueabihf/bat
          rm bat-v*-unknown-linux-gnueabihf.tar.gz

          nameregex='^bat-v\d[\d.]+?\d?-x86_64-unknown-linux-gnu\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/sharkdp/bat/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar --wildcards --strip-components=1 -C bin/x86_64 -xvf bat-v*-unknown-linux-gnu.tar.gz bat-v*-unknown-linux-gnu/bat
          rm bat-v*-unknown-linux-gnu.tar.gz

      - name: Commit and push to repository
        run: |
          git config --global user.name "eggbean"
          git config --global user.email 815311+eggbean@users.noreply.github.com
          git add --all
          git status
          tag="$(curl -s https://api.github.com/repos/sharkdp/bat/releases/latest | jq -r '.tag_name')"
          git commit -m "[Action] Upgrade bat to ${tag}"
          git push
