name: Upgrade rclone
on:
  [workflow_dispatch]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and extract tarballs
        run: |
          nameregex='^rclone-v\d[\d.]+?\d?-linux-amd64\.zip$'
          url="$(curl -s https://api.github.com/repos/rclone/rclone/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          file="${url##*/}"
          wget -q "${url}"
          unzip "${file}"
          rm "${file%.*}"/{git-log.txt,README.*}
          mv "${file%.*}"/rclone bin/x86_64
          mv "${file%.*}"/rclone.1 bin/man/man1
          gzip -f bin/man/man1/rclone.1
          rm "${file}"
          bin/x86_64/rclone completion bash > bin/completions/rclone.bash

          nameregex='^rclone-v\d[\d.]+?\d?-linux-arm-v7\.zip$'
          url="$(curl -s https://api.github.com/repos/rclone/rclone/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          file="${url##*/}"
          wget -q "${url}"
          unzip "${file}"
          rm "${file%.*}"/{git-log.txt,README.*,rclone.1}
          mv "${file%.*}"/rclone bin/armv7l
          rm "${file}"

          nameregex='^rclone-v\d[\d.]+?\d?-linux-arm64\.zip$'
          url="$(curl -s https://api.github.com/repos/rclone/rclone/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          file="${url##*/}"
          wget -q "${url}"
          unzip "${file}"
          rm "${file%.*}"/{git-log.txt,README.*,rclone.1}
          mv "${file%.*}"/rclone bin/aarch64
          rm "${file}"

      - name: Commit and push to repository
        run: |
          git config --global user.name "eggbean"
          git config --global user.email 815311+eggbean@users.noreply.github.com
          git add --all
          git status
          tag="$(curl -s https://api.github.com/repos/rclone/rclone/releases/latest | jq -r '.tag_name')"
          git commit -m "Upgrade rclone to ${tag}"
          git push
