name: Upgrade hyperfine
on:
  [workflow_dispatch]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and extract tarballs
        run: |
          nameregex='^hyperfine-v\d[\d.]+?\d?-aarch64-unknown-linux-gnu\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/sharkdp/hyperfine/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar --wildcards --strip-components=1 -C bin/aarch64 -xvf hyperfine-v*-unknown-linux-gnu.tar.gz hyperfine-v*-unknown-linux-gnu/hyperfine
          tar --wildcards --strip-components=1 -C bin/man/man1 -xvf hyperfine-v*-unknown-linux-gnu.tar.gz hyperfine-v*-unknown-linux-gnu/hyperfine.1
          gzip -f bin/man/man1/hyperfine.1 2>/dev/null
          tar --wildcards --strip-components=2 -C bin/bash-completions -xvf hyperfine-v*-unknown-linux-gnu.tar.gz hyperfine-v*-unknown-linux-gnu/autocomplete/hyperfine.bash
          tar --wildcards --strip-components=2 -C bin/zsh-completions -xvf hyperfine-v*-unknown-linux-gnu.tar.gz hyperfine-v*-unknown-linux-gnu/autocomplete/_hyperfine
          rm hyperfine-v*-unknown-linux-gnu.tar.gz

          nameregex='^hyperfine-v\d[\d.]+?\d?-arm-unknown-linux-gnueabihf\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/sharkdp/hyperfine/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar --wildcards --strip-components=1 -C bin/armv7l -xvf hyperfine-v*-unknown-linux-gnueabihf.tar.gz hyperfine-v*-unknown-linux-gnueabihf/hyperfine
          rm hyperfine-v*-unknown-linux-gnueabihf.tar.gz

          nameregex='^hyperfine-v\d[\d.]+?\d?-x86_64-unknown-linux-gnu\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/sharkdp/hyperfine/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar --wildcards --strip-components=1 -C bin/x86_64 -xvf hyperfine-v*-unknown-linux-gnu.tar.gz hyperfine-v*-unknown-linux-gnu/hyperfine
          rm hyperfine-v*-unknown-linux-gnu.tar.gz

      - name: Commit and push to repository
        run: |
          git config --global user.name "eggbean"
          git config --global user.email 815311+eggbean@users.noreply.github.com
          git add --all
          git status
          tag="$(curl -s https://api.github.com/repos/sharkdp/hyperfine/releases/latest | jq -r '.tag_name')"
          git commit -m "[Action] Upgrade hyperfine to ${tag}"
          git push
