name: Upgrade glow
on:
  [workflow_dispatch]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and extract tarballs
        run: |
          nameregex='^glow_\d[\d.]+?\d?_linux_x86_64\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/charmbracelet/glow/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar -C bin/x86_64 -xvf glow_*_linux_x86_64.tar.gz glow
          rm glow_*_linux_x86_64.tar.gz

          nameregex='^glow_\d[\d.]+?\d?_linux_arm64\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/charmbracelet/glow/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar -C bin/aarch64 -xvf glow_*_linux_arm64.tar.gz glow
          rm glow_*_linux_arm64.tar.gz

          nameregex='^glow_\d[\d.]+?\d?_linux_armv7\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/charmbracelet/glow/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar -C bin/armv7l -xvf glow_*_linux_armv7.tar.gz glow
          rm glow_*_linux_armv7.tar.gz

      - name: Commit and push to repository
        run: |
          git config --global user.name "eggbean"
          git config --global user.email 815311+eggbean@users.noreply.github.com
          git add --all
          git status
          tag="$(curl -s https://api.github.com/repos/charmbracelet/glow/releases/latest | jq -r '.tag_name')"
          git commit -m "Upgrade glow to ${tag}"
          git push
